### ISSUE TITLE
Microphone stopped working after the last apt upgrade

### ISSUE THREAD

**Issue by Rom888** [lemmyg/t2-apple-audio-dsp#12] opened 2023-11-09 06:56 UTC
The microphone was working, but stopped working after the last 'sudo apt upgrade'
```
$ pw-record /tmp/test.wav
remote error: id=0 seq:39 res:-32 (Broken pipe): connection error
stream node 105 unconnected
```
machine:
```
Ubuntu 23.04
6.5.9-t2-lunar

MacBookPro16.1
Intel Core i9 2.3g

hybrid graphics:
Intel UHD graphics 630
AMD radeon pro 5500M

macOs: Ventura 13.2
```

**Comment by lemmyg** [comment] 2023-11-09 07:54
Try to follow again the steps to install Debian upstream repo stuff.

**Comment by Rom888** [comment] 2023-11-09 11:23
Tried, rebooted and got the same error.

I see some errors in the log, for example:
```
$ journalctl --boot=0 | grep pipewire > /tmp/pipewire-logs.txt

Nov 09 14:16:42 mb pipewire[2946]: mod.filter-chain: control 'Amplitude (dB)' can not be set: No such file or directory
Nov 09 14:16:42 mb pipewire[2946]: mod.filter-chain: control 'Amplitude (dB)' can not be set: No such file or directory
Nov 09 14:16:42 mb pipewire[2946]: mod.jackdbus-detect: Failed to receive jackdbus reply: org.freedesktop.DBus.Error.ServiceUnknown: The name org.jackaudio.service was not provided by any .service files
```
[pipewire-logs.txt](https://github.com/lemmyg/t2-apple-audio-dsp/files/13307494/pipewire-logs.txt)

**Comment by lemmyg** [comment] 2023-11-09 19:22
that error look like from this plugin
https://github.com/lemmyg/t2-apple-audio-dsp/blob/mic/config/10-t2_mic.conf#L57

**Comment by lemmyg** [comment] 2023-11-09 21:07
Finally I found that I'm getting same parameters warning. Im fix it.

Any they are just warnings. I don't think is the cause of your issue.

Please mic volumes are at 100%.

Specially apple mic input that would be the source of the mic DSP.

**Comment by Rom888** [comment] 2023-11-10 06:10
I checked it and yes, all volumes are 100%.
```
$ pactl list sources > /tmp/list-sources.txt
```
[list-sources.txt](https://github.com/lemmyg/t2-apple-audio-dsp/files/13316150/list-sources.txt)

Still the same error:
```
$ pw-record /tmp/test.wav
remote error: id=0 seq:39 res:-32 (Broken pipe): connection error
stream node 130 unconnected
```

**Comment by lemmyg** [comment] 2023-11-10 06:54
Try

pw-cli list-nodes

You find out which node is 130.

**Comment by Rom888** [comment] 2023-11-10 13:09
I see the max id = 98.
[list-objects.txt](https://github.com/lemmyg/t2-apple-audio-dsp/files/13319538/list-objects.txt)

**Comment by lemmyg** [comment] 2023-11-10 20:04
it looks like MacBook Pro T2 DSP Mic doesnt for me too.

I didnt do any change recently, so I dont know why.

MacBook Pro T2 DSP HeadSetMic seems working.
I didn't use those mics for a while as usually I use an external webcam for my meetings

**Comment by codingnooob** [comment] 2023-11-11 08:04
Same issue here on a Macbook Pro 16.2 running Linux Mint 21.2 x86_64 (Cinnamon DE) with Kernel 6.6.1-t2-jammy. Along with the microphone input not working, the facetime camera freezes and the bluetooth headset connects and disconnects repeatedly as well. I suspect all of these issues are somehow related. I also got this weird glitch where the input devices duplicate themselves in the Cinnamon sound panel.
![MicIssue](https://github.com/lemmyg/t2-apple-audio-dsp/assets/66186626/1b62fa94-0046-457a-9d5c-4d38de777e97)

**Comment by mahboobkarimian** [comment] 2023-11-11 17:03
For me, the error is:

```
Nov 11 18:00:03 -MacBookPro kernel: x86/PAT: pipewire:38335 map pfn RAM range req uncached-minus for [mem 0x67680000-0x676b0fff], got write-back
Nov 11 18:00:03 -MacBookPro kernel: pipewire[38343]: segfault at 0 ip 00007fd7db4023c1 sp 00007fd7db3fea00 error 4 in sc4_1882.so[7fd7db400000+5000] likely on CPU 9 (core 3, socket 0)
Nov 11 18:00:04 -MacBookPro systemd[4005]: pipewire.service: Main process exited, code=dumped, status=11/SEGV
Nov 11 18:00:04 -MacBookPro systemd[4005]: pipewire.service: Failed with result 'core-dump'.
Nov 11 18:00:04 -MacBookPro wireplumber[38336]: disconnected from pipewire
Nov 11 18:00:04 -MacBookPro systemd[4005]: pipewire.service: Scheduled restart job, restart counter is at 43.
Nov 11 18:00:04 -MacBookPro systemd[4005]: Stopped pipewire.service - PipeWire Multimedia Service.
Nov 11 18:00:04 -MacBookPro systemd[4005]: Started pipewire.service - PipeWire Multimedia Service.
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'meter_in' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'meter_out' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'clip_in' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'clip_out' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'bypass' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'cbe_0' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.filter-chain: control 'Amplitude (dB)' can not be set: No such file or directory
Nov 11 18:00:04 -MacBookPro pipewire[38362]: mod.jackdbus-detect: Failed to receive jackdbus reply: org.freedesktop.DBus.Error.ServiceUnknown: The name org.jackaudio.service was not provided by any .service files
```

Look at the segfault from pipewire.

**Comment by mahboobkarimian** [comment] 2023-11-11 18:42
Update: seems upgrading kernel to 6.5.9 resolved this problem. I will test this furthur and report here

**Comment by lemmyg** [comment] 2023-11-11 21:05
I made some changes
https://github.com/lemmyg/t2-apple-audio-dsp/commit/9422c57caeb54fde45121b9ea31628080da9d3bd
looks like we can capture mic 3 channels any more.

**Comment by mahboobkarimian** [comment] 2023-11-12 12:02
Seems this resolved the problem.

> I made some changes https://github.com/lemmyg/t2-apple-audio-dsp/releases/tag/mic-v0.4.0-1 looks like we cant capture mic 3 channels any more.

**Comment by lemmyg** [comment] 2023-11-12 12:34
Cool. Resolving the issue.

**Closed** 2023-11-12 12:34 UTC

**Comment by Rom888** [comment] 2023-11-12 13:56
It works now, thank you!
